"""Workspace rule for downloading subpackage dependencies."""

load("//lib/aec:package.bzl", download_aec = "download")
load("//lib/bison:package.bzl", download_bison = "download")
load("//lib/blas:package.bzl", download_blas = "download")
load("//lib/boost:package.bzl", download_boost = "download")
load("//lib/bz2:package.bzl", download_bz2 = "download")
load("//lib/ceres:package.bzl", download_ceres = "download")
load("//lib/cmark:package.bzl", download_cmark = "download")
load("//lib/curl:package.bzl", download_curl = "download")
load("//lib/deflate:package.bzl", download_deflate = "download")
load("//lib/eigen:package.bzl", download_eigen = "download")
load("//lib/exiv2:package.bzl", download_exiv2 = "download")
load("//lib/expat:package.bzl", download_expat = "download")
load("//lib/ffi:package.bzl", download_ffi = "download")
load("//lib/fftw:package.bzl", download_fftw = "download")
load("//lib/flex:package.bzl", download_flex = "download")
load("//lib/gcc:package.bzl", download_gcc = "download")
load("//lib/gdal:package.bzl", download_gdal = "download")
load("//lib/geos:package.bzl", download_geos = "download")
load("//lib/geotiff:package.bzl", download_geotiff = "download")
load("//lib/gflags:package.bzl", download_gflags = "download")
load("//lib/gif:package.bzl", download_gif = "download")
load("//lib/glog:package.bzl", download_glog = "download")
load("//lib/gmp:package.bzl", download_gmp = "download")
load("//lib/grass:package.bzl", download_grass = "download")
load("//lib/hdf:package.bzl", download_hdf = "download")
load("//lib/hdf5:package.bzl", download_hdf5 = "download")
load("//lib/iconv:package.bzl", download_iconv = "download")
load("//lib/imath:package.bzl", download_imath = "download")
load("//lib/jpegturbo:package.bzl", download_jpegturbo = "download")
load("//lib/jq:package.bzl", download_jq = "download")
load("//lib/lcms:package.bzl", download_lcms = "download")
load("//lib/lz4:package.bzl", download_lz4 = "download")
load("//lib/lzma:package.bzl", download_lzma = "download")
load("//lib/lzo:package.bzl", download_lzo = "download")
load("//lib/m4:package.bzl", download_m4 = "download")
load("//lib/mpdecimal:package.bzl", download_mpdecimal = "download")
load("//lib/mpfr:package.bzl", download_mpfr = "download")
load("//lib/musl:package.bzl", download_musl = "download")
load("//lib/ncurses:package.bzl", download_ncurses = "download")
load("//lib/oniguruma:package.bzl", download_oniguruma = "download")
load("//lib/opencv:package.bzl", download_opencv = "download")
load("//lib/openexr:package.bzl", download_openexr = "download")
load("//lib/openjpeg:package.bzl", download_openjpeg = "download")
load("//lib/openssl:package.bzl", download_openssl = "download")
load("//lib/pano13:package.bzl", download_pano13 = "download")
load("//lib/png:package.bzl", download_png = "download")
load("//lib/proj:package.bzl", download_proj = "download")
load("//lib/protobuf:package.bzl", download_protobuf = "download")
load("//lib/python:package.bzl", download_python = "download")
load("//lib/quirc:package.bzl", download_quirc = "download")
load("//lib/readline:package.bzl", download_readline = "download")
load("//lib/sdl:package.bzl", download_sdl = "download")
load("//lib/sqlite:package.bzl", download_sqlite = "download")
load("//lib/suitesparse:package.bzl", download_suitesparse = "download")
load("//lib/szip:package.bzl", download_szip = "download")
load("//lib/tcl:package.bzl", download_tcl = "download")
load("//lib/tiff:package.bzl", download_tiff = "download")
load("//lib/tirpc:package.bzl", download_tirpc = "download")
load("//lib/vigra:package.bzl", download_vigra = "download")
load("//lib/webp:package.bzl", download_webp = "download")
load("//lib/xml:package.bzl", download_xml = "download")
load("//lib/xslt:package.bzl", download_xslt = "download")
load("//lib/z:package.bzl", download_z = "download")
load("//lib/zstd:package.bzl", download_zstd = "download")

def download_lib():
    """Download all library sources."""
    download_aec()
    download_bison()
    download_blas()
    download_boost()
    download_bz2()
    download_ceres()
    download_cmark()
    download_curl()
    download_deflate()
    download_eigen()
    download_exiv2()
    download_expat()
    download_ffi()
    download_fftw()
    download_flex()
    download_gcc()
    download_gdal()
    download_geos()
    download_geotiff()
    download_gflags()
    download_gif()
    download_glog()
    download_gmp()
    download_grass()
    download_hdf()
    download_hdf5()
    download_iconv()
    download_imath()
    download_jpegturbo()
    download_jq()
    download_lcms()
    download_lz4()
    download_lzma()
    download_lzo()
    download_m4()
    download_mpdecimal()
    download_mpfr()
    download_musl()
    download_ncurses()
    download_oniguruma()
    download_opencv()
    download_openexr()
    download_openjpeg()
    download_openssl()
    download_pano13()
    download_png()
    download_proj()
    download_protobuf()
    download_python()
    download_quirc()
    download_readline()
    download_sdl()
    download_sqlite()
    download_suitesparse()
    download_szip()
    download_tcl()
    download_tiff()
    download_tirpc()
    download_vigra()
    download_webp()
    download_xml()
    download_xslt()
    download_z()
    download_zstd()
