"""Workspace rule for downloading subpackage dependencies."""

load("//lib/ceres:package.bzl", "download_ceres")
load("//lib/curl:package.bzl", "download_curl")
load("//lib/deflate:package.bzl", "download_deflate")
load("//lib/eigen:package.bzl", "download_eigen")
load("//lib/exiv2:package.bzl", "download_exiv2")
load("//lib/expat:package.bzl", "download_expat")
load("//lib/ffi:package.bzl", "download_ffi")
load("//lib/fftw:package.bzl", "download_fftw")
load("//lib/gdal:package.bzl", "download_gdal")
load("//lib/gflags:package.bzl", "download_gflags")
load("//lib/gif:package.bzl", "download_gif")
load("//lib/glog:package.bzl", "download_glog")
load("//lib/gmp:package.bzl", "download_gmp")
load("//lib/hdf5:package.bzl", "download_hdf5")
load("//lib/jpeg_turbo:package.bzl", "download_jpeg_turbo")
load("//lib/lz4:package.bzl", "download_lz4")
load("//lib/lzma:package.bzl", "download_lzma")
load("//lib/lzo:package.bzl", "download_lzo")
load("//lib/mpfr:package.bzl", "download_mpfr")
load("//lib/open_jpeg:package.bzl", "download_open_jpeg")
load("//lib/open_ssl:package.bzl", "download_open_ssl")
load("//lib/pano13:package.bzl", "download_pano13")
load("//lib/png:package.bzl", "download_png")
load("//lib/proj:package.bzl", "download_proj")
load("//lib/python:package.bzl", "download_python")
load("//lib/readline:package.bzl", "download_readline")
load("//lib/sqlite:package.bzl", "download_sqlite")
load("//lib/suite_sparse:package.bzl", "download_suite_sparse")
load("//lib/tiff:package.bzl", "download_tiff")
load("//lib/vigra:package.bzl", "download_vigra")
load("//lib/webp:package.bzl", "download_webp")
load("//lib/z:package.bzl", "download_z")
load("//lib/zstd:package.bzl", "download_zstd")

def download_lib():
    """Download all library sources."""
    download_ceres()
    download_curl()
    download_deflate()
    download_eigen()
    download_exiv2()
    download_expat()
    download_ffi()
    download_fftw()
    download_gdal()
    download_gflags()
    download_gif()
    download_glog()
    download_gmp()
    download_hdf5()
    download_jpeg_turbo()
    download_lz4()
    download_lzma()
    download_lzo()
    download_mpfr()
    download_open_jpeg()
    download_open_ssl()
    download_pano13()
    download_png()
    download_proj()
    download_python()
    download_readline()
    download_sqlite()
    download_suite_sparse()
    download_tiff()
    download_vigra()
    download_webp()
    download_z()
    download_zstd()
